### PR TITLE
Bring Task Improvements

### PR DESCRIPTION
**Pull request by PokeCodec**
Cherry picked from pret

### CODE REVIEW

**Review by Ryuhouji — COMMENTED** [review]
What prompted this contribution? I don't know who you are, would like to find out.

**Comment by Ryuhouji** [comment]
I don't see any reason to merge this PR, and it comes to my attention that you may have been the person trying to taint pret's repos. So, i'm not interested in your contributions.

**Comment by PokeCodec** [comment]
Literally not but you keep making stuff up

**Comment by PokeCodec** [comment]
Really tired of this guilt by association nonsense tbh.

**Pull request closed without merging**
