### PR TITLE
Better indentation for achievement definitions

### PR DESCRIPTION
**Pull request by Scott-TT**
## Description
Improved (hopefully) legibility around achievement definitions. No technical change.

### CODE REVIEW

**Comment by Ryuhouji** [comment]
This would be fine, if I was done editing everything here. All this does is make it harder for me, if, say, I add an achievement that has a longer name. Then I have to reindent everything. 

Changes like this are unecessary, as EE is an ever-expanding repository. If you want to optimize functions, that's one thing, remove unused functions, that's another, but just changing the format like this for no reason other than to make it look better to you is not what I'm looking for. As a reminder, I'm the primary developer of the game, so if it inconveniences me, then it probably shouldn't be added.

**Comment by Scott-TT** [comment]
I thought this was a collaborative project. If you'd rather make it easy on yourself than enable contributors to do just that : contribute to what's on-going instead of just fixing your bugs for you... My bad.

I'd wish you luck, but I'm a believer in reaping what you sow, and wishing you to be alone on your throne seems harsh. Anyways, I'm out.

**Comment by Ryuhouji** [comment]
This isn't just about me, all this change would do is increase the amount of work required in the future for anyone, including myself to make changes to these constants. There are ZERO other arrays that are organized in this way in the rest of the codebase, so it wouldn't even be adhering to an already existing paradigm. The flags and the variables use this sort of indentation, which is fine, but this is not acceptable for arrays, and multidimensional arrays, because they are already overly complicated to work with.

**Comment by Ryuhouji** [comment]
If you want to change this PR to only have changes to the defines, and NOT the array, then i am okay with it. But again, even if you do this for one array in one file, there are thousands of arrays in the game that are NOT organized in this way.

**Pull request closed without merging**
